
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:199 (message)"
      - "CMakeLists.txt:38 (project)"
    message: |
      The target system is: Generic - 0.0.0 - 
      The host system is: Darwin - 22.3.0 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:38 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/local/bin/x86_64-elf-gcc 
      Build flags: -g;-c;-O0;-m32;-fno-pie;-fno-stack-protector;-fno-asynchronous-unwind-tables
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        /Users/bytedance/Documents/os/make_os/start/start3/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:38 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/bytedance/Documents/os/make_os/start/start3/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-YB0UMH"
      binary: "/Users/bytedance/Documents/os/make_os/start/start3/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-YB0UMH"
    cmakeVariables:
      CMAKE_C_FLAGS: "-g -c -O0 -m32 -fno-pie -fno-stack-protector -fno-asynchronous-unwind-tables"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: /Users/bytedance/Documents/os/make_os/start/start3/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-YB0UMH
        
        Run Build Command(s):/Applications/CLion.app/Contents/bin/ninja/mac/ninja -v cmTC_90c66 && [1/2] /usr/local/bin/x86_64-elf-gcc   -g -c -O0 -m32 -fno-pie -fno-stack-protector -fno-asynchronous-unwind-tables  -fdiagnostics-color=always   -v -o CMakeFiles/cmTC_90c66.dir/CMakeCCompilerABI.c.obj -c /Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeCCompilerABI.c
        Using built-in specs.
        COLLECT_GCC=/usr/local/bin/x86_64-elf-gcc
        Target: x86_64-elf
        Configured with: ../configure --target=x86_64-elf --prefix=/usr/local/Cellar/x86_64-elf-gcc/12.2.0 --infodir=/usr/local/Cellar/x86_64-elf-gcc/12.2.0/share/info/x86_64-elf --disable-nls --without-isl --without-headers --with-as=/usr/local/opt/x86_64-elf-binutils/bin/x86_64-elf-as --with-ld=/usr/local/opt/x86_64-elf-binutils/bin/x86_64-elf-ld --enable-languages=c,c++
        Thread model: single
        Supported LTO compression algorithms: zlib
        gcc version 12.2.0 (GCC) 
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-g' '-c' '-O0' '-m32' '-fno-pie' '-fno-stack-protector' '-fno-asynchronous-unwind-tables' '-v' '-o' 'CMakeFiles/cmTC_90c66.dir/CMakeCCompilerABI.c.obj' '-c' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_90c66.dir/'
         /usr/local/Cellar/x86_64-elf-gcc/12.2.0/libexec/gcc/x86_64-elf/12.2.0/cc1 -quiet -v /Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeCCompilerABI.c -quiet -dumpdir CMakeFiles/cmTC_90c66.dir/ -dumpbase CMakeCCompilerABI.c.c -dumpbase-ext .c -m32 -mtune=generic -march=x86-64 -g -O0 -version -fdiagnostics-color=always -fno-pie -fno-stack-protector -fno-asynchronous-unwind-tables -o /var/folders/30/cmv9c_5j3mq_kthx63sb1t5c0000gn/T//ccdnCKVJ.s
        GNU C17 (GCC) version 12.2.0 (x86_64-elf)
        	compiled by GNU C version Apple LLVM 13.1.6 (clang-1316.0.21.2.5), GMP version 6.2.1, MPFR version 4.1.0, MPC version 1.2.1, isl version none
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring nonexistent directory "/usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/12.2.0/../../../../x86_64-elf/sys-include"
        ignoring nonexistent directory "/usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/12.2.0/../../../../x86_64-elf/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/12.2.0/include
         /usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/12.2.0/include-fixed
        End of search list.
        GNU C17 (GCC) version 12.2.0 (x86_64-elf)
        	compiled by GNU C version Apple LLVM 13.1.6 (clang-1316.0.21.2.5), GMP version 6.2.1, MPFR version 4.1.0, MPC version 1.2.1, isl version none
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        Compiler executable checksum: 08fbc53bda09edf0e38c54289ad252c4
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-g' '-c' '-O0' '-m32' '-fno-pie' '-fno-stack-protector' '-fno-asynchronous-unwind-tables' '-v' '-o' 'CMakeFiles/cmTC_90c66.dir/CMakeCCompilerABI.c.obj' '-c' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_90c66.dir/'
         /usr/local/opt/x86_64-elf-binutils/bin/x86_64-elf-as -v --gdwarf-5 --32 -o CMakeFiles/cmTC_90c66.dir/CMakeCCompilerABI.c.obj /var/folders/30/cmv9c_5j3mq_kthx63sb1t5c0000gn/T//ccdnCKVJ.s
        GNU assembler version 2.39 (x86_64-elf) using BFD version (GNU Binutils) 2.39
        COMPILER_PATH=/usr/local/Cellar/x86_64-elf-gcc/12.2.0/libexec/gcc/x86_64-elf/12.2.0/:/usr/local/Cellar/x86_64-elf-gcc/12.2.0/libexec/gcc/x86_64-elf/12.2.0/:/usr/local/Cellar/x86_64-elf-gcc/12.2.0/libexec/gcc/x86_64-elf/:/usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/12.2.0/:/usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/
        LIBRARY_PATH=/usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/12.2.0/
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-g' '-c' '-O0' '-m32' '-fno-pie' '-fno-stack-protector' '-fno-asynchronous-unwind-tables' '-v' '-o' 'CMakeFiles/cmTC_90c66.dir/CMakeCCompilerABI.c.obj' '-c' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_90c66.dir/CMakeCCompilerABI.c.'
        [2/2] : && /usr/local/bin/x86_64-elf-gcc -g -c -O0 -m32 -fno-pie -fno-stack-protector -fno-asynchronous-unwind-tables -v CMakeFiles/cmTC_90c66.dir/CMakeCCompilerABI.c.obj -o cmTC_90c66   && :
        Using built-in specs.
        COLLECT_GCC=/usr/local/bin/x86_64-elf-gcc
        Target: x86_64-elf
        Configured with: ../configure --target=x86_64-elf --prefix=/usr/local/Cellar/x86_64-elf-gcc/12.2.0 --infodir=/usr/local/Cellar/x86_64-elf-gcc/12.2.0/share/info/x86_64-elf --disable-nls --without-isl --without-headers --with-as=/usr/local/opt/x86_64-elf-binutils/bin/x86_64-elf-as --with-ld=/usr/local/opt/x86_64-elf-binutils/bin/x86_64-elf-ld --enable-languages=c,c++
        Thread model: single
        Supported LTO compression algorithms: zlib
        gcc version 12.2.0 (GCC) 
        COMPILER_PATH=/usr/local/Cellar/x86_64-elf-gcc/12.2.0/libexec/gcc/x86_64-elf/12.2.0/:/usr/local/Cellar/x86_64-elf-gcc/12.2.0/libexec/gcc/x86_64-elf/12.2.0/:/usr/local/Cellar/x86_64-elf-gcc/12.2.0/libexec/gcc/x86_64-elf/:/usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/12.2.0/:/usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/
        LIBRARY_PATH=/usr/local/Cellar/x86_64-elf-gcc/12.2.0/lib/gcc/x86_64-elf/12.2.0/
        COLLECT_GCC_OPTIONS='-g' '-c' '-O0' '-m32' '-fno-pie' '-fno-stack-protector' '-fno-asynchronous-unwind-tables' '-v' '-o' 'cmTC_90c66' '-mtune=generic' '-march=x86-64' '-dumpdir' 'cmTC_90c66.'
        x86_64-elf-gcc: warning: CMakeFiles/cmTC_90c66.dir/CMakeCCompilerABI.c.obj: linker input file unused because linking not done
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:38 (project)"
    checks:
      - "Check for working C compiler: /usr/local/bin/x86_64-elf-gcc"
    directories:
      source: "/Users/bytedance/Documents/os/make_os/start/start3/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-U0UeAb"
      binary: "/Users/bytedance/Documents/os/make_os/start/start3/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-U0UeAb"
    cmakeVariables:
      CMAKE_C_FLAGS: "-g -c -O0 -m32 -fno-pie -fno-stack-protector -fno-asynchronous-unwind-tables"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: /Users/bytedance/Documents/os/make_os/start/start3/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-U0UeAb
        
        Run Build Command(s):/Applications/CLion.app/Contents/bin/ninja/mac/ninja -v cmTC_25f79 && [1/2] /usr/local/bin/x86_64-elf-gcc   -g -c -O0 -m32 -fno-pie -fno-stack-protector -fno-asynchronous-unwind-tables  -fdiagnostics-color=always -o CMakeFiles/cmTC_25f79.dir/testCCompiler.c.obj -c /Users/bytedance/Documents/os/make_os/start/start3/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-U0UeAb/testCCompiler.c
        [2/2] : && /usr/local/bin/x86_64-elf-gcc -g -c -O0 -m32 -fno-pie -fno-stack-protector -fno-asynchronous-unwind-tables  CMakeFiles/cmTC_25f79.dir/testCCompiler.c.obj -o cmTC_25f79   && :
        x86_64-elf-gcc: warning: CMakeFiles/cmTC_25f79.dir/testCCompiler.c.obj: linker input file unused because linking not done
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1102 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineASMCompiler.cmake:127 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:39 (enable_language)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      x86_64-elf-gcc (GCC) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
